#!/bin/bash

while read matrix
do
  ID=`echo $matrix | cut -d',' -f1`
  name=`echo $matrix | cut -d',' -f2`

  rm -rf $name report."$name"
  ./build/rewrite "$ID" &> report."$name"
done < matrix.ID.name

